package BusinessLayer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author malik
 */
public class employeeFrame extends javax.swing.JFrame {

    /**
     * Creates new form employeeFrame
     */
    public employeeFrame() throws SQLException {
        initComponents();
        loadDetainEmployee(new employeeDAO().getAllEmployees());
    }

    private void loadDetainEmployee(List<Employee> e ){
      DefaultTableModel tableModel= (DefaultTableModel) jTableEmployess.getModel();
      tableModel.setRowCount(0);
      for(Employee itr: e){
          tableModel.addRow(new Object[]{itr.getId(),itr.getName(),itr.getPosition(),itr.getSalary()});
      }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfSalary = new javax.swing.JTextField();
        tfPosition = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmployess = new javax.swing.JTable();
        btnADD = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Salary");

        jLabel3.setText("Position");

        jLabel4.setText("Name");

        tfID.setColumns(5);

        tfSalary.setColumns(5);

        tfPosition.setColumns(5);

        tfName.setColumns(5);

        jTableEmployess.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "ID", "Name", "Position", "Salary"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEmployess);

        btnADD.setBackground(new java.awt.Color(51, 102, 0));
        btnADD.setForeground(new java.awt.Color(255, 255, 255));
        btnADD.setText("Add");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(102, 102, 0));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(153, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfPosition, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                        .addComponent(tfName))
                                .addGap(155, 155, 155)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnADD, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(40, 40, 40))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jScrollPane1)
                                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel3)
                                                        .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tfPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(tfSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel4)
                                                                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(btnADD)
                                                .addGap(27, 27, 27)
                                                .addComponent(btnUpdate)
                                                .addGap(33, 33, 33)
                                                .addComponent(btnDelete)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTableEmployess.getModel();

        int selesctedrow=jTableEmployess.getSelectedRow();
        if(selesctedrow==-1){
            JOptionPane.showMessageDialog(null,"Please select a record ");
            return ;
        }
        else {
            int rowdata = (int) defaultTableModel.getValueAt(selesctedrow,0);
            try {
                new employeeDAO().deleteEmployee(rowdata);
                loadDetainEmployee(new employeeDAO().getAllEmployees());
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }

        }

    }

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {
       int id= Integer.parseInt(tfID.getText());
       double salary= Double.parseDouble(tfSalary.getText());
       String position = tfPosition.getText();
       String name = tfName.getText();

            Employee e = new Employee();
            e.setPosition(position);
            e.setName(name);
            e.setSalary(salary);
            e.setId(id);
        try {
            new employeeDAO().insertEmployee(e);
            loadDetainEmployee(new employeeDAO().getAllEmployees());

        } catch (SQLException ex) {
            throw new RuntimeException(ex);
        }
tfID.setText("");
        tfName.setText("")
        ;
        tfPosition.setText("");
        tfSalary.setText("");

    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTableEmployess.getModel();

        int selesctedrow=jTableEmployess.getSelectedRow();
        if(selesctedrow==-1){
            JOptionPane.showMessageDialog(null,"Please select a record to update ");
            return ;
        }
        else {

            int rowdata = (int) defaultTableModel.getValueAt(selesctedrow,0);
            try {
                new employeeDAO().deleteEmployee(rowdata);
                loadDetainEmployee(new employeeDAO().getAllEmployees());
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }

        }
        int id= Integer.parseInt(tfID.getText());
        double salary= Double.parseDouble(tfSalary.getText());
        String position = tfPosition.getText();
        String name = tfName.getText();

        Employee e = new Employee();
        e.setPosition(position);
        e.setName(name);
        e.setSalary(salary);
        e.setId(id);
        try {
            new employeeDAO().insertEmployee(e);
            loadDetainEmployee(new employeeDAO().getAllEmployees());

        } catch (SQLException ex) {
            throw new RuntimeException(ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new employeeFrame().setVisible(true);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmployess;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPosition;
    private javax.swing.JTextField tfSalary;
    // End of variables declaration
}

